Q1.Numpy array operations


In [1]:
import numpy as np

A = np.array([
    [12, 5, 8, 20],
    [7, 15, 3, 11],
    [25, 9, 18, 6],
    [10, 14, 2, 16]
])
mean = np.mean(A, axis=1)
binary_matrix = (A > mean[:, np.newaxis]).astype(int)
count = np.sum(A > mean[:, np.newaxis], axis=1)

max_count = np.max(count)
rows = np.where(count == max_count)[0]

print("Row means:")
print(mean)

print("\nBinary matrix:")
print(binary_matrix)

print("\nCount:")
print(count)

print("\nMaximum count:", max_count)
print("Rows:", rows + 1)

Row means:
[11.25  9.   14.5  10.5 ]

Binary matrix:
[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]

Count:
[2 2 2 2]

Maximum count: 2
Rows: [1 2 3 4]


Q2.   X = np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15, 115, 9] ]) For each column: 1. Calculate the mean and standard deviation. 2. Identify values satisfying: ∣x−μ∣>2σ 3. Replace such values with the corresponding column median. 4. Do this without modifying non-outlier values.

In [2]:
import numpy as np

X = np.array([
    [10, 100, 5],
    [12, 110, 6],
    [11, 105, 7],
    [13, 500, 6],
    [14, 108, 8],
    [15, 115, 9]
])
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
outlier_mask = np.abs(X - mean) > 2 * std
median = np.median(X, axis=0)
X_clean = np.where(outlier_mask, median, X)

print(mean)
print(std)
print(outlier_mask)
print(median)
print(X_clean)

[ 12.5        173.           6.83333333]
[  1.70782513 146.31017281   1.34370962]
[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False False]]
[ 12.5 109.    6.5]
[[ 10. 100.   5.]
 [ 12. 110.   6.]
 [ 11. 105.   7.]
 [ 13. 109.   6.]
 [ 14. 108.   8.]
 [ 15. 115.   9.]]


Q3.  import pandas as pd  df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],  'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],  'Gender': ['F','M','F','M','M','F','F','M'],  'Marks': [85,72,91,65,78,88,95,70], 'Attendance': [92,81,96,72,85,90,98,75] })  

In [3]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A','B','C','D','E','F','G','H'],
    'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],
    'Gender': ['M','F','F','M','F','F','M','F'],
    'Marks': [85,72,91,65,78,88,95,70],
    'Attendance': [92,81,96,72,85,90,98,75]
})
avg = df.groupby('Department')['Marks'].mean()
gender_avg = df.groupby(
    ['Department', 'Gender']
)['Marks'].mean()
highest = df.loc[
    df.groupby('Department')['Marks'].idxmax()
]
mean = df.groupby(
    'Department'
)['Marks'].transform('mean')

above_average = df[
    df['Marks'] > mean
]
attendance_avg = df.groupby(
    'Department'
)['Attendance'].mean()

highest_attendance = attendance_avg.idxmax()

print("1. Department Average:")
print(avg)

print("\n2. Department + Gender Average:")
print(gender_avg)

print("\n3. Highest Marks:")
print(highest)

print("\n4. Above Department Average:")
print(above_average)

print("\n5. Highest Average Attendance:")
print(attendance_avg)

print("\nDepartment:", highest_attendance)

1. Department Average:
Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64

2. Department + Gender Average:
Department  Gender
CSE         F         75.0
            M         90.0
ECE         F         83.0
            M         65.0
Name: Marks, dtype: float64

3. Highest Marks:
  Student Department Gender  Marks  Attendance
6       G        CSE      M     95          98
2       C        ECE      F     91          96

4. Above Department Average:
  Student Department Gender  Marks  Attendance
0       A        CSE      M     85          92
2       C        ECE      F     91          96
5       F        ECE      F     88          90
6       G        CSE      M     95          98

5. Highest Average Attendance:
Department
CSE    89.00
ECE    83.25
Name: Attendance, dtype: float64

Department: CSE


Q4.  df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],  'Name': ['A','B','C','A','D','B','E'], 'Age': [20,21,22,20,23,21,24],  'Score': [80,75,90,85,88,75,92] })  Perform: 1. Identify duplicated IDs. 2. For each ID, determine whether its records are identical. 3. If multiple records exist for an ID, retain the record having the highest Score. 4. Produce a clean DataFrame containing exactly one record per ID. 5. Report how many records were removed.

In [4]:
import pandas as pd

df = pd.DataFrame({
    'ID': [101,102,103,101,104,102,105],
    'Name': ['A','B','C','D','E','F','G'],
    'Age': [20,21,22,23,21,24,21],
    'Score': [80,75,90,85,88,75,92]
})


duplicated_ids = df.loc[
    df['ID'].duplicated(keep=False), 'ID'
].unique()

print("Duplicated IDs:")
print(duplicated_ids)

for id_value in duplicated_ids:
    records = df[df['ID'] == id_value]

    identical = records.drop(
        columns='ID'
    ).nunique().eq(1).all()

    print("\nID:", id_value)
    print(records)

    if identical:
        print("Records are identical")
    else:
        print("Records are not identical")
clean_df = (
    df.sort_values(
        ['ID', 'Score'],
        ascending=[True, False],
        kind='stable'
    )
    .drop_duplicates('ID', keep='first')
    .sort_values('ID')
    .reset_index(drop=True)
)

print("\nClean DataFrame:")
print(clean_df)


removed = len(df) - len(clean_df)

print("\nRecords removed:", removed)

Duplicated IDs:
[101 102]

ID: 101
    ID Name  Age  Score
0  101    A   20     80
3  101    D   23     85
Records are not identical

ID: 102
    ID Name  Age  Score
1  102    B   21     75
5  102    F   24     75
Records are not identical

Clean DataFrame:
    ID Name  Age  Score
0  101    D   23     85
1  102    B   21     75
2  103    C   22     90
3  104    E   21     88
4  105    G   21     92

Records removed: 2


Q5.  df = pd.DataFrame({ 'Date': [ '2026-01-01', '2026-01-02', '2026-01-04', '2026-01-05', '2026-01-08', '2026-01-09' ],  'Sales': [100,120,150,130,180,200] })  Perform: 1. Convert Date into a proper datetime column. 2. Detect the missing dates. 3. Reindex the DataFrame to contain every date between the minimum and maximum date. 4. Keep missing sales as NaN.

In [5]:
import pandas as pd

df = pd.DataFrame({
    'Date': [
        '2026-01-01',
        '2026-01-02',
        '2026-01-04',
        '2026-01-05',
        '2026-01-08',
        '2026-01-09'
    ],
    'Sales': [100,120,150,130,180,200]
})
df['Date'] = pd.to_datetime(df['Date'])

full_dates = pd.date_range(
    df['Date'].min(),
    df['Date'].max(),
    freq='D'
)

missing_dates = full_dates.difference(
    df['Date']
)

print("Missing dates:")
print(missing_dates)

df = df.set_index('Date')
df = df.reindex(full_dates)
df.index.name = 'Date'

df['Rolling_Average'] = (
    df['Sales']
    .rolling(window=3, min_periods=1)
    .mean()
)

print("\nDataFrame:")
print(df)

date = df['Rolling_Average'].idxmax()

print("\nMaximum rolling average date:")
print(date)

print("\nMaximum rolling average:")
print(df['Rolling_Average'].max())

Missing dates:
DatetimeIndex(['2026-01-03', '2026-01-06', '2026-01-07'], dtype='datetime64[ns]', freq=None)

DataFrame:
            Sales  Rolling_Average
Date                              
2026-01-01  100.0            100.0
2026-01-02  120.0            110.0
2026-01-03    NaN            110.0
2026-01-04  150.0            135.0
2026-01-05  130.0            140.0
2026-01-06    NaN            140.0
2026-01-07    NaN            130.0
2026-01-08  180.0            180.0
2026-01-09  200.0            190.0

Maximum rolling average date:
2026-01-09 00:00:00

Maximum rolling average:
190.0


Q6.  P = np.array([ [1, 2], [4, 6], [7, 3], [2, 8], [9, 5] ])  Construct a 5×5 matrix where element (i,j) contains the Euclidean distance between points i and j. The solution must: ● use NumPy broadcasting; ● contain no for or while loop; ● have zeros on the diagonal; ● produce a symmetric matrix. Then identify the pair of points having the maximum distance.

In [8]:
import numpy as np

P = np.array([
    [1, 2],
    [4, 6],
    [7, 3],
    [2, 8],
    [9, 5]
])

diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]

D = np.sqrt(
    np.sum(diff ** 2, axis=2)
)
np.fill_diagonal(D, 0)

print("Distance matrix:")
print(D)
i, j = np.unravel_index(
    np.argmax(D),
    D.shape
)

print("\nMaximum distance:")
print(D[i, j])

print("\nPair of points:")
print(i, j)

print("\nPoint", i, ":", P[i])
print("Point", j, ":", P[j])

Distance matrix:
[[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]

Maximum distance:
8.54400374531753

Pair of points:
0 4

Point 0 : [1 2]
Point 4 : [9 5]


Q7. Take 10 datasets from kaggle (Tabular datasets e.g. weather dataset, housing dataset, titanic dataset, etc.) Perform exploratory data analysis on the dataset using seaborn , matplotlib. (Draw graphs like bar chart, line chart, scatter plots, etc. and explain the insights). Also clean the dataset accordingly.

In [12]:
import pandas as pd

df = pd.read_csv("tested.csv")

print(df.head())
print(df.shape)
print(df.columns)

   PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  
(418, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
 